//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Application
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class PayerPayee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayerPayee()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int PPId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string DOB { get; set; }
        public string Email { get; set; }
        public int UserDetailsUserId { get; set; }
    
        public virtual UserDetails UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }

        public bool AddPayerPayee(PayerPayee obj)
        {
            using (var context = new FinanceEDMContainer())
            {
                //obj.UserDetailsUserId = Session.SessionID;
                obj.UserDetailsUserId = 1;
                context.PayerPayees.Add(obj);
                context.SaveChanges();
            }
            return true;
        }

        public bool RemovePayerPayee(PayerPayee obj)
        {
            using (var context = new FinanceEDMContainer())
            {
                context.PayerPayees.Remove(obj);
                context.SaveChanges();
            }
            return true;
        }

        public void UpdatePayerPayee(int id, PayerPayee obj)
        {
            using (var context = new FinanceEDMContainer())
            {
                var record = context.PayerPayees.SingleOrDefault(e => e.PPId == id);
                record = obj;
            }
        }

        public List<PayerPayee> AllPPRecords()
        {
            using (var context = new FinanceEDMContainer())
            {
                return context.PayerPayees.ToList();
            }
        }
    }
}
