//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Application
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public bool Recuring { get; set; }
        public System.DateTime Date { get; set; }
        public string TransactionType { get; set; }
        public int UserDetailsUserId { get; set; }
    
        public virtual PayerPayee PayerPayee { get; set; }
        public virtual UserDetails UserDetail { get; set; }

        public bool AddTransaction(Transaction obj)
        {
            using (var context = new FinanceEDMContainer())
            {
                obj.UserDetailsUserId = Session.SessionID;
                context.Transactions.Add(obj);
                context.SaveChanges();
            }
            return true;
        }

        public bool RemoveTransaction(Transaction obj)
        {
            using (var context = new FinanceEDMContainer())
            {
                context.Transactions.Remove(obj);
                context.SaveChanges();
            }
            return true;
        }

        public void UpdateTransaction()
        {

        }
        
        public Transaction GetTransaction(String Date)
        {
            using (var context = new FinanceEDMContainer())
            {
                return context.Transactions.Where(e => e.Date == Date);
            }

        }

        public void GetTransaction(int Id)
        {

        }

    }
}
